GRIFFIERS = [('A. Badermann', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A. Belhadi', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('A. Bohlmeijer', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('A. de Vlieger-Mandour', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A. Elligens', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('A. Heinen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A. Hielkema', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('A. Jansen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A. Jansen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A. Jansen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('A. Jansen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('A. Koelewijn', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('A. Landstra', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('A. Nobel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A. Tanyildiz', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A. Teggelaar', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('A. Verhoeven', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('A. Verhoeven', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A. Vranken', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A. W.C.M. Frings', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('A. Wijker-Dekker', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A. Wilpstra-Foppen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('A. Wilpstra-Foppen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A.A. Dijk', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('A.C. Hummel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('A.C. Karels', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('A.C. Karels', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A.C.P. Witsiers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A.E. Maas', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A.E. Paulus', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A.E. van Duinen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('A.E.M. Lever', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('A.F. Hooghuis', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('A.G. de Vries-Biharie', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('A.G. de Vries-Biharie', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.G. Sijbrands', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('A.G.P.M. Zweipfenning', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('A.J. Jansen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('A.J. Jansen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.J. Kinds', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('A.J. Kuipers', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.J. Soede', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.J. van Rossum', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A.J. Veenboer', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.J.H. van der Donk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('A.J.J. Sterks', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('A.J.M. van Hees', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('A.L. Abdoellakhan', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('A.L. van der Duijn Schouten', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('A.L. van Driel Kluit', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.M. Pasmans', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('A.M. Slierendrecht', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('A.M. Veenstra', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('A.M.E.A. Neuwahl', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.M.L. Hanrath', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.M.M. Chevalier', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('A.M.S.J. Baggerman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('A.R. Vlierhuis', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('A.S. Hamans', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('A.S. Sanchit-Premchand', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('A.W. Martens', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('A.W.C.M. Frings', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('Arends', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('Arntz', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('B. Klein Nulent', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('B. Ley-Nell', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('B. Montagne', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('B. van Dael', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('B. van Dokkum', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('B. Vonck', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('B.C. van Sprundel-Thelosen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('B.E. Giesen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('B.E. Giesen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('B.G.M. Laarhoven', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('B.L. Meijer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('B.M. van der Meide', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('B.M.A. Laheij', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('B.P.C. Vonck', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('B.V.A. Corstens', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('B.V.A. Corstens', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('B.V.K. de Louw', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('C. Blankenstein', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('C. Groenewegen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('C. Kuiper', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('C. Kuiper', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('C. Pasteuning', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('C. Schrammen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('C. Sparreboom', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('C.A. Blankenstein', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('C.A.F. Kalb', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('C.A.M. van Deventer-Lustberg', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('C.C.H. Hersbach', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('C.C.H. Hersbach', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('C.C.J. de Wilde', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('C.D.V. Efstratiades', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('C.E. Delvaux', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('C.E.C.M. van Roosmalen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('C.F. Donner-Haan', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('C.F. Donner-Haan', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('C.F.E.M. Mes', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('C.G.M. van Ede', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('C.H. Vrijsen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('C.H.R. Mattheussens', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('C.I. Heijkoop', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('C.M. Steemers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('C.M.J. Rouwers', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('C.S. de Waal', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('C.T. Hofman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('C.W. Steenkist', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('D. Alblas', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('D. de Vries', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('D. de Vries', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('D. Meyer-de Beer', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('D. Milosavljević', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('D. Rietberg', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('D. Tieleman', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('D.C. van der Ven', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('D.D. van Loopik', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('D.D.R.H. Lechanteur', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('D.G.T. de Hoop', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('D.H. ter Beek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('D.H.J. Laeven', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('D.L. Bolleboom', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('D.M.M. Luijckx', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('D.P. van Middelkoop', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('D.S Barthel', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('D.S. Barthel', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('D.S.A.W. Raes', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('D.SA.W. Raes', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('E. Degen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('E. Diele', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('E. Diele', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('E. Huis-Grondman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('E. Keles', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('E. Mengerink', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('E. Mulder', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('E. Naaijen-van Kleunen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('E. Nolles', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('E. Petrusma', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('E. van der Zweep', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('E. van Kampen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('E.A. Binnema', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('E.A. van der Meel', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('E.A. Vermunt', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('E.A.D. Horn', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('E.C. Koziolek-Stoof', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('E.C. Petrusma', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('E.C. Petrusma', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('E.C. Stoof', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('E.D. Dalman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('E.D. Dalman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('E.D.H. Nanninga', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('E.H. Kalse-Spoon', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('E.H. Kalse-Spoon', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('E.H. Kalse‑Spoon', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('E.H. Kalse‑Spoon', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('E.H. Mazel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('E.H. Pot', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('E.H.W. Schierbeek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('E.L. Denters', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('E.M. de Buur', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('E.M. Ouwehand', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('E.M.L. Kousen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('E.P. van der Zalm', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('E.P.W. Kwakman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('E.P.W. Kwakman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('E.R. Fernandez', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('E.T. de Jong', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('E.T. Rietbroek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('E.W. Seylhouwer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('F. Bouman', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('F. Grundmeijer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('F. Nales', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('F. Vermeij', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('F. Voskamp', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('F. Willems', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('F.A. Timmers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('F.B. van der Maesen de Sombreff', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('F.C. van Zuijlen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('F.E.M. Boon', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('F.G.A. Claessen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('F.J.M. Schoonbrood', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('F.J.M. Stolk', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('F.K. Heiting', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('F.M. van den Assem', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('F.P. van Straelen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('F.P. van Straelen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('F.W. de Lange', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('G. Kootstra', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('G.A Verhoeven', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('G.A. Kajim-Panjer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('G.J. Deen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('G.J. Machwirth', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('G.J. Tingen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('G.J. Tingen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('G.M.T.M. Sips', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('G.S.M. van Duinkerken', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('H. de Vries', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('H. Herweijer', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('H. Oranje', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('H. Philips', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('H. Sabanovic', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('H. Spaargaren', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('H.A. Hulst', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('H.A. Komduur', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('H.A. Komduur', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('H.C. Hagen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('H.D. Sebel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('H.E. Melissen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('H.H. Riemeijer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('H.J. Habetian', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('H.J. Hovinga', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('H.J. van der Meiden', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('H.J. Verspuij-Fung', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('H.J.J.M. Kock', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('H.L.A. van Kats', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('H.R.A. Horring', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('Huizenga', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('I. Boland', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('I. Powell-Koleva', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('I.A. Siskina', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('I.C. de Zeeuw-\'t Lam', 'http: // standaarden.overheid.nl / owms / terms / Rechtbank_Midden-Nederland'),
             ('I.C. Hof', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('I.M. Wijnker-Duiven', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('I.M.C. van Og', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('I.N. Powell', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('I.N. van Soest', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('I.S. Ouwehand', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('I.S. Ouwehand', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J. Bosveld', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('J. Bruin', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('J. de Graaf', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('J. de Graaf', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J. de Vries', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J. Poggemeier', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('J. van Mazijk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('J. Verbeek', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.A. Lammertink', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('J.A. Leijten', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('J.A. Meijer - Habraken', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('J.A. Meijer-Habraken', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('J.A.A. van Roessel', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.A.W. van Leeuwen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.C. de Grauw', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('J.C.E. Krikke', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('J.C.E. Krikke', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('J.F.A. Bleichrodt', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('J.F.M. Emons', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('J.G. Bos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('J.G.J. Geerlings', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('J.H. Bosveld', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('J.H. Roelfsema', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.H.C.W. Vonk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('J.J. den Broeder', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.J.M. Tol', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('J.J.M.A. Poppelaars', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.J.P. Bruin', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('J.J.P.M. van Gestel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('J.M. Van Sambeek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('J.M. van Sambeek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('J.M.M. Bancken', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('J.M.M. van Dalen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('J.M.M. Versteegh-Janssen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('J.N. Buddeke', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('J.N. Witsen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.P. Braam', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('J.P. Braam', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('J.P. Brand', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('J.P. Brand', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('J.R. de Savornin Lohman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('J.R. Leegsma', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('J.R. van Veen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('J.S.S. Hupkes', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.V. Baan-de Vries', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('J.V. Veldwijk', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.V. Vreugdenhil', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('J.W.E. Pinckaers', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('J.W.J. Reuvers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('J.W.J.M van Rijt', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('J.W.J.M. van Rijt', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('K. Mestrom', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('K. Naganathar', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('K. Naganathar', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('K.H.E. Swinkels', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('K.K.E. Blom', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('K.R. van Renswoude', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('K.S. Man', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('K.V. van Weert', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('L. El Ouardiji', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('L. El Ouardiji', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('L. Fernandez Ferreiro', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('L. Groenendijk', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('L. Heekelaar', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('L. Ruizendaal-van der Veen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('L. Stoelinga', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('L. ten Hove', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('L. ten Hove', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('L. van Broekhoven', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('L.A. Super', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('L.A. Super', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('L.C. Dankbaar', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('L.C. Lodeweges', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('L.C. Trommel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('L.C.M. Wijgerde', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('L.D. Wevers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('L.E. Hesselink', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('L.E. Mollerus', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('L.E.E. Konings', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('L.H.J. van Haarlem', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('L.J.N, van der Linden', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('L.J.N. van der Linden', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('L.M. Janssens-Kleijn', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('L.M. Melenhorst', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('L.N. Foppen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('L.N. Linzey', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('L.S. Kors', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('L.S. Lodder', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('Landstra', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('M. Azmi', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('M. Belhaj', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M. Belhaj', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('M. Belhaj', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M. Bos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('M. Bos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('M. Bos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M. de Graaf', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M. de Graaf', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M. den Toom', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M. Duifhuizen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M. Duursma', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M. Gayir', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M. Géron', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('M. Journee', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M. Journée', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M. Journée', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M. Khababi', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('M. Kool', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('M. Kos', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M. Lammerse', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('M. Noordegraaf', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('M. Oosterhuis', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M. Pier', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M. Priem', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M. Rijsdijk', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M. Scheele', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M. Tijsma', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M. Traousis - van Wingaarden', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('M. Traousis – van Wingaarden', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('M. van Dalen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('M. van der Elst', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('M. van Emmerik', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('M. van Excel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('M. van Velzen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M. Vogel-Carprieaux', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.A. de Rooij', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('M.A. Graaff-Haasnoot', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.A. Knikkink', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M.A. Nieuwenhuizen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.A.A. Traousis', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('M.A.C. Heyltjes', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('M.A.E. Planken', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.A.J. Arts', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M.A.J. van Beek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M.A.L. Verbruggen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('M.B. van Zantvoort', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('M.B. Volp', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('M.B.G. Cox-Vorage', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('M.B.L. van der Weele', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('M.D. Moeke', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('M.D. Pielaat', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M.E. Sjouke', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M.E.C. Bakker', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('M.F. van den Brink', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('M.G. Alderlieste', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.G. Ligthart', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('M.G. Smeenk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('M.H. Boomsma', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('M.H. Dijkman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('M.H. Kuggeleijn-Jansen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.H. van Kersbergen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('M.H. van Limpt', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M.H. Vonk-Menger', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('M.H.A. de Graaf', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('M.H.M. Steigenga-Gerritsen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('M.H.Y Snoeren-Bos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('M.H.Y. Snoeren-Bos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('M.I. Tuk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('M.I.P. Buteijn', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('M.J. Beckers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('M.J. van der Zijpp', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.J.F.J. van Beek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('M.J.G. Driessen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.J.S. Kempers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M.L. Bressers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('M.L. Pijpers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M.L.F. de Leeuw', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('M.L.M van Loo', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.L.M. van Loo', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.M. van Driel', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.M. van Driel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('M.M. van Luijk-Salomons', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('M.P. Osinga Sanders', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('M.P.C. Moers-Anssems', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('M.P.J.M. van Grinsven', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.P.M. Veerman-Timmer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('M.R. Broeze', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('M.R. Marinus', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('M.R. van Kerkwijk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('M.T. Petersen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('M.V.T.K. Oei', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('M.W. Hulsman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('M.W. Venderbos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('N. Brouwer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('N. Graumans', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('N. Joacim', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('N. Joacim', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('N. van Asten', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('N. van der Kroft', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('N. van. Asten', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('N.A. D\'Hoore', 'http: // standaarden.overheid.nl / owms / terms / Rechtbank_Zeeland-West-Brabant'),
             ('N.A. D’Hoore', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('N.A.H. Kosters', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('N.C. Correa', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('N.D.T. Pieters', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('N.E. Joacim', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('N.G.U. Wasch', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('N.I. Breunese-van Goor', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('N.J. Brouwer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('N.J. Brouwer', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('N.J.R. Kalaykhan', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('N.J.R. Kalaykhan', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('N.K. de Bruin', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('N.L. Adam', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('N.M. Zandbergen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('N.R. Hoogenberk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('N.R. Peters', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('N.S.J. Letschert', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('N.T. Zijlstra', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('O. Asafiati', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('O.G.J. Stroek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('O.G.J. Stroek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('O.H.M. Leito', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('P. Deinum', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('P. Jasperse', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('P. Klein', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('P. Lodder', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('P. Oudkerk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('P. Plambeck', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('P.A. Melse', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('P.C. Stroebel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('P.C. van der Vlugt', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('P.E.A. Chao', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('P.F. Lammers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('P.F.H.M. Terstegge', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('P.F.W. Tuit', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('P.H.M. Verdonschot', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('P.J. Naus', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('P.J.H. Bijleveld', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('P.L.M.M. Mulders', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('P.M. Beishuizen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('P.M. de Kruif', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('P.M. Saedt', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('P.M. van den Brekel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('P.M.M. van Zanten', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('P.M.M. van Zanten', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('P.W. Hogenbirk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('P.W. Hogenbirk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('Pranger', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('Pullens', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('R. Boerlage', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('R. Dijkman', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('R. Grimbergen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R. Groeneveld', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('R. Klingers', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R. Kroon - Overdijk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('R. Kroon-Overdijk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('R. Pronk', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('R. Stijnen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('R. Teuben', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R. van der Vecht', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('R. van Diest', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('R. van Heusden', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.A. Schaapsmeerders', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('R.A.E. Bach', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('R.C. Kroeze', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('R.C. Smeets', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('R.E. Toonen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('R.E. Toonen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('R.E.A. Matulewicz', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.E.J Jansen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('R.F.J. Bindels', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.G. Cremers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('R.G. Kamphof', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('R.G. van der Korput', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Oost-Brabant'),
             ('R.H.L. Dallinga', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.I. ten Cate', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('R.I. Ten Cate', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('R.I.Y. Lap', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.J. Tolner', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('R.J.R. Hazen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.J.R. van Broekhoven', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('R.K. Witteveen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('R.M.N. van den Hazel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('R.P. Evegaars', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('R.P. Stehouwer', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('R.P.F. Boermans', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.R. Jacobs', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.S.D. Ramrattansing', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('R.S.H.M. Hussien', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('R.S.H.M. Hussien', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('R.V. van Vliet', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('S. Bazaz', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('S. de Koning', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S. Langeveld-Mak', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S. Niane-van de Put', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S. Vermeulen', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S. Westerhof', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Midden-Nederland'),
             ('S. Zwemstra', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S.A Lemmens', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('S.A. Lemmens', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('S.C. van Tuyll van Serooskerken', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S.E. Berghout', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('S.E. Reichardt', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S.H.H. Slaats', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('S.I. Havinga', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('S.I. van der Hoek', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('S.J.L. Crombach', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S.J.R.R. Brock', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S.J.R.R. Vreugdenhil-Brock', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('S.L. Mehlbaum', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('S.M. Koning', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('S.M. van Ditmarsch', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('S.M.M. Bolt-Hulsen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('S.P. Jadoenathmisier', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('S.R. Jonkergouw', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('S.R.N. Parlevliet', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('S.S. Autar', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('S.S. Soylu', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('Starreveld', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('T. Ali', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('T. Gelo', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('T. Güzelsari', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('T. Hartsuiker', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('T. Kuiper', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('T. Pourjalili', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('T. Pourjalili', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('T. Rijs', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('T. Rijs', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('T. van Goeverden-Clarenbeek', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('T.B. Both', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('T.C.A. Hofman-Aupers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Nederland'),
             ('T.E. Bouwmeester', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('T.J.M. Schilder', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('T.M. Horsten-Kuijpers', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('T.R. Oosterhoff-Vos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('Terhell', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('V. Naaijkens', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('V. van Dorst', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('V.E.A. Naaijkens', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('V.H.Y. Huijts', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('V.Y. van Almelo', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('Van der Zee-Venema', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('Veenstra', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('W. Dijkshoorn', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('W. Dijkshoorn', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('W. Evenhuis', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('W. Niekel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('W. Niekel', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('W. Roozeboom', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('W. van den Berg', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('W.A.M. Bocken', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Limburg'),
             ('W.C. Knoester', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Gelderland'),
             ('W.D. Kamphorst-Timmer', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('W.G. van Gastelen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('W.H. Bolt', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Amsterdam'),
             ('W.I.K. Baart', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Noord-Holland'),
             ('W.J. Steenbergen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('W.J.C. Goorden', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Zeeland-West-Brabant'),
             ('W.J.C. Robben', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('W.M. Boer', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('W.M. Colpa', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('W.M. Swinkels', 'http://standaarden.overheid.nl/owms/terms/Centrale_Raad_van_Beroep'),
             ('W.S. van Helvoort', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('Werdmüller von Elgg', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('Wijmenga', 'http://standaarden.overheid.nl/owms/terms/Gerechtshof_Arnhem-Leeuwarden'),
             ('Y. Soffner', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('Y. van Arnhem', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Overijssel'),
             ('Y.C. Visser', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('Y.D. Ancion', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('Y.E. de Loos', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Den_Haag'),
             ('Y.F.J. Fransen', 'http://standaarden.overheid.nl/owms/terms/Rechtbank_Rotterdam'),
             ('Y.M. van Soest-Ahlers', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State'),
             ('Y.R. Boonstra-Herwijnen', 'http://standaarden.overheid.nl/owms/terms/College_van_Beroep_voor_het_bedrijfsleven'),
             ('E.K. van Leening', 'http://standaarden.overheid.nl/owms/terms/Raad_van_State')]
